---
title: "Untitled"
output: html_document
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(purrr)
library(lubridate)
library(viridis)
library(extrafont)
library(wesanderson)
library(patchwork)
library(ggtext)
library(tidyr)
library(readxl)
```


```{r}
sites <- read_csv("/Users/jessicakeast/Downloads/sites.csv")
temp_points <- read_csv("/Users/jessicakeast/Downloads/temperature-points.csv")
points <- read_csv("/Users/jessicakeast/Downloads/points.csv")

power_data_same_sites <- read_csv("power_data_same_sites.csv")

font_import(pattern="RobotoSlab")
```

```{r read power data}
read_month_data <- function(quar_month, folder){
list.files(str_c("/Users/jessicakeast/Downloads/", quar_month, folder), full.names = TRUE) %>% 
  map(read_csv) %>% 
  reduce(rbind)
}

mon_list <- list("2019_Q1_v3/Jan", "2019_Q1_v3/Feb", "2019_Q1_v3/Mar", "2019_Q2_v3/Apr", "2019_Q2_v3/May", "2019_Q2_v3/Jun", "2019_Q3_v3/Jul", "2019_Q3_v3/Aug", "2019_Q3_v3/Sep", "2019_Q4_v3/Oct", "2019_Q4_v3/Nov", "2019_Q4_v3/Dec")
power_data2 <- NULL

for (month in mon_list){
  print(month)
  power_data2 <- read_month_data(month, "/power/") %>% 
    left_join(points, by = c("ee_site_id", "regname")) %>% 
    left_join(sites, by = c("ee_site_id")) %>% 
    mutate(circuit_label_type_desc = case_when(
      str_detect(circuit_label, "(L|l)ight") | str_detect(equipment_type_desc, "(L|l)ight") |
        str_detect(circuit_label, "(P|p)lug") | str_detect(equipment_type_desc, "(P|p)lug") |
        str_detect(circuit_label, "(O|o)utlet") | str_detect(equipment_type_desc, "(O|o)utlet") ~ "Lighting and/or Outlets", TRUE ~ circuit_label_type_desc),
      min_t = min_t + hours(tz_utc_offset),
      month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
      hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
      date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
    group_by(ee_site_id, regname, date, month, hour, hz, cz, circuit_label_type_desc) %>% 
    summarize(kW_hour = sum(power)) %>% 
    group_by(date, hour, month, hz, cz, circuit_label_type_desc) %>% 
    summarize(mean_power = mean(kW_hour), median_power = median(kW_hour), max_power=max(kW_hour), min_power=min(kW_hour)) %>% 
    rbind(power_data2)
}


power_data2 <- power_data2 %>% 
  mutate(category = case_when(
    circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Garbage Disposal", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range") ~ "Other",
    str_detect(circuit_label_type_desc, "AC") ~ "AC",
    str_detect(circuit_label_type_desc, "(W|w)ater") ~ "Water Heaters",
    str_detect(circuit_label_type_desc, "Heat") | str_detect(circuit_label_type_desc, "Furnace") ~ "Heating",
  circuit_label_type_desc %in% c("Electric Vehicle Charger", "Hot Tub", "Lighting and/or Outlets") | str_detect(circuit_label_type_desc, "Other") ~ "Other",
  str_detect(circuit_label_type_desc, "Mains") ~ "Mains",
  TRUE ~ circuit_label_type_desc)#,
  # month = case_when(
  #   month == "01" ~ "Jan",
  #   month == "02" ~ "Feb",
  #   month == "03" ~ "Mar",
  #   month == "04" ~ "Apr",
  #   month == "05" ~ "May",
  #   month == "06" ~ "Jun",
  #   month == "07" ~ "Jul",
  #   month == "08" ~ "Aug",
  #   month == "09" ~ "Sep",
  #   month == "10" ~ "Oct",
  #   month == "11" ~ "Nov",
  #   month == "12" ~ "Dec")
  )

power_data2$month <- factor(power_data2$month, levels = month.abb)

#write_csv(power_data2, "power_data2.csv")
```

```{r load data, same sites}
jan_15 <- read_csv("/Users/jessicakeast/Downloads/2019_Q1_v3/Jan/power/power-fifteen_20190115.csv")

jan_properties <- unique(jan_15$ee_site_id)


mon_list <- list("2019_Q1_v3/Jan", "2019_Q1_v3/Feb", "2019_Q1_v3/Mar", "2019_Q2_v3/Apr", "2019_Q2_v3/May", "2019_Q2_v3/Jun", "2019_Q3_v3/Jul", "2019_Q3_v3/Aug", "2019_Q3_v3/Sep", "2019_Q4_v3/Oct", "2019_Q4_v3/Nov", "2019_Q4_v3/Dec")
power_data_same_sites <- NULL

for (month in mon_list){
  print(month)
  power_data_same_sites <- read_month_data(month, "/power/") %>% 
    left_join(points, by = c("ee_site_id", "regname")) %>% 
    left_join(sites, by = c("ee_site_id")) %>% 
    filter(ee_site_id %in% jan_properties) %>% 
    mutate(circuit_label_type_desc = case_when(
      str_detect(circuit_label, "(L|l)ight") | str_detect(equipment_type_desc, "(L|l)ight") |
        str_detect(circuit_label, "(P|p)lug") | str_detect(equipment_type_desc, "(P|p)lug") |
        str_detect(circuit_label, "(O|o)utlet") | str_detect(equipment_type_desc, "(O|o)utlet") ~ "Lighting and/or Outlets", TRUE ~ circuit_label_type_desc),
      min_t = min_t + hours(tz_utc_offset),
      month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
      hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
      date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
    group_by(ee_site_id, regname, date, month, hour, hz, cz, circuit_label_type_desc) %>% 
    summarize(kW_hour = sum(power)) %>% 
    group_by(date, hour, month, hz, cz, circuit_label_type_desc) %>% 
    summarize(mean_power = mean(kW_hour), median_power = median(kW_hour), max_power=max(kW_hour), min_power=min(kW_hour)) %>% 
    rbind(power_data_same_sites)
}


power_data_same_sites <- power_data_same_sites %>% 
  mutate(category = case_when(
    circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Garbage Disposal", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range") ~ "Other",
    str_detect(circuit_label_type_desc, "AC") ~ "AC",
    str_detect(circuit_label_type_desc, "(W|w)ater") ~ "Water Heaters",
    str_detect(circuit_label_type_desc, "Heat") | str_detect(circuit_label_type_desc, "Furnace") ~ "Heating",
  circuit_label_type_desc %in% c("Electric Vehicle Charger", "Hot Tub", "Lighting and/or Outlets") | str_detect(circuit_label_type_desc, "Other") ~ "Other",
  str_detect(circuit_label_type_desc, "Mains") ~ "Mains",
  TRUE ~ circuit_label_type_desc)#,
  # month = case_when(
  #   month == "01" ~ "Jan",
  #   month == "02" ~ "Feb",
  #   month == "03" ~ "Mar",
  #   month == "04" ~ "Apr",
  #   month == "05" ~ "May",
  #   month == "06" ~ "Jun",
  #   month == "07" ~ "Jul",
  #   month == "08" ~ "Aug",
  #   month == "09" ~ "Sep",
  #   month == "10" ~ "Oct",
  #   month == "11" ~ "Nov",
  #   month == "12" ~ "Dec")
  )

power_data_same_sites$month <- factor(power_data_same_sites$month, levels = month.abb)

#write_csv(power_data_same_sites, "power_data_same_sites.csv")
```

```{r read temperature data}
temperature_data <- NULL

for (month in mon_list){
  print(month)
  temperature_data <- read_month_data(month, "/temperature/") %>% 
    left_join(temp_points, by = c("ee_site_id", "transmitter_code")) %>% 
    left_join(sites, by = c("ee_site_id")) %>% 
    mutate(min_t = min_t + hours(tz_utc_offset),
      month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
      hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
      date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
    group_by(date, hour, month, hz, cz) %>% 
    summarize(mean_outdoor_temp = mean(na.omit(temp[interior_exterior==2])), 
              median_outdoor_temp = median(na.omit(temp[interior_exterior==2])), 
              max_outdoor_temp=max(na.omit(temp[interior_exterior==2])), 
              min_outdoor_temp=min(na.omit(temp[interior_exterior==2])),
              mean_indoor_temp = mean(na.omit(temp[interior_exterior==1])),
              median_indoor_temp = median(na.omit(temp[interior_exterior==1])),
              max_indoor_temp = max(na.omit(temp[interior_exterior==1])),
              min_indoor_temp = min(na.omit(temp[interior_exterior==1]))) %>% 
    rbind(temperature_data) 
}

temperature_data <- temperature_data %>% 
    mutate(month = case_when(
      month == "01" ~ "Jan",
      month == "02" ~ "Feb",
      month == "03" ~ "Mar",
      month == "04" ~ "Apr",
      month == "05" ~ "May",
      month == "06" ~ "Jun",
      month == "07" ~ "Jul",
      month == "08" ~ "Aug",
      month == "09" ~ "Sep",
      month == "10" ~ "Oct",
      month == "11" ~ "Nov",
      month == "12" ~ "Dec"))

temperature_data2 <- na.omit(temperature_data)
temperature_data2$month <- factor(temperature_data2$month, levels = month.abb)


```

```{r}
num_uses <- points %>% filter(ee_site_id %in% jan_properties) %>% 
  mutate(category = case_when(
    circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Garbage Disposal", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range") ~ "Other",
    str_detect(circuit_label_type_desc, "AC") ~ "AC",
    str_detect(circuit_label_type_desc, "(W|w)ater") ~ "Water Heaters",
    str_detect(circuit_label_type_desc, "Heat") | str_detect(circuit_label_type_desc, "Furnace") ~ "Heating",
  circuit_label_type_desc %in% c("Electric Vehicle Charger", "Hot Tub", "Lighting and/or Outlets") | str_detect(circuit_label_type_desc, "Other") ~ "Other",
  str_detect(circuit_label_type_desc, "Mains") ~ "Mains",
  TRUE ~ circuit_label_type_desc)) %>% 
  group_by(circuit_label_type_desc, category) %>% 
  summarize(number = n())

num_uses2 <- points %>% filter(ee_site_id %in% jan_properties)

```


```{r}
power_data_same_sites %>% 
  group_by(hour, category, month) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  filter(!is.na(category), category != "Mains") %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=category), stat = "identity")+
  facet_wrap(~month)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Month by Circuit Category (Same Sites)", y = "Load/Energy (kWh)", x = "Hour", fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = c("#5BBCD6", "#FF0000", "#91A737", "#F49C00", "#32806E"),
                    labels = c("AC (22 sites)", "Heating (73 sites)", "Other (73 sites)", "Solar (4 sites)", "Water Heaters (53 sites)"))+ #, "#257BA0"
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))
```



```{r plot appliances}
power_data_same_sites %>% 
  filter(circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range")) %>% 
  group_by(hour, month, circuit_label_type_desc) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=circuit_label_type_desc), stat = "identity")+
  scale_fill_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Clothes Dryer (69 sites*)", "Clothes Washer (48 sites*)", "Dishwasher (47 sites*)", "Microwave (12 sites*)", "Refrigerator/Freezer (25 sites*)", "Stove/Oven/Range (68 sites*)"))+
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  facet_wrap(~month)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power Used by Appliances", y = "Load/Energy (kWh)", x = NULL, fill = NULL, caption = "*For many sites, appliances were grouped in the 'other' category.\nAppliances for these sites are not included in this visual.")

power_data_same_sites %>% 
  filter(circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range")) %>% 
  group_by(hour, circuit_label_type_desc) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=circuit_label_type_desc), stat = "identity")+
  scale_fill_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Clothes Dryer (69 sites*)", "Clothes Washer (48 sites*)", "Dishwasher (47 sites*)", "Microwave (12 sites*)", "Refrigerator/Freezer (25 sites*)", "Stove/Oven/Range (68 sites*)"))+
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power Used by Appliances", y = "Load/Energy (kWh)", x = NULL, fill = NULL, caption = "*For many sites, appliances were grouped in the 'other' category.\nAppliances for these sites are not included in this visual.")

power_data_same_sites %>% 
  filter(circuit_label_type_desc %in% c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range")) %>% 
  group_by(month, circuit_label_type_desc) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_bar(aes(x=month, y=mean_power, fill=circuit_label_type_desc), stat = "identity")+
  scale_fill_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Clothes Dryer (69 sites*)", "Clothes Washer (48 sites*)", "Dishwasher (47 sites*)", "Microwave (12 sites*)", "Refrigerator/Freezer (25 sites*)", "Stove/Oven/Range (68 sites*)"))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power Used by Appliances", y = "Load/Energy (kWh)", x = NULL, fill = NULL, caption = "*For many sites, appliances were grouped in the 'other' category.\nAppliances for these sites are not included in this visual.")
```



```{r}
power_data_same_sites %>% 
  filter(category == "Heating") %>% 
  group_by(month, circuit_label_type_desc) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_bar(aes(x=circuit_label_type_desc, y=mean_power, fill=circuit_label_type_desc), stat = "identity")+
  facet_wrap(~month)+
  scale_fill_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Ducted Heatpump (34 sites)*", "Ductless Heatpump (9 sites)", "Electric Baseboard Heaters (16 sites)", "Electric Furnace (39 sites)", "Gas Furnance (Component) (24 sites)", "Other Zonal Heat (11 sites)"))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank())+
  labs(title = "2019 EULR Average Power Used by Heaters (Same Sites)", y = "Load/Energy (kWh)", x = NULL, fill = NULL, caption = "*Ducted heatpumps are used for air conditioning at some sites,\nexplaining the higher load/energy in the Summer months.")


heating <- NULL

for (month in mon_list){
  heating <- read_month_data(month, "/power/") %>%
  left_join(points, by = c("ee_site_id", "regname")) %>%
  left_join(sites, by = c("ee_site_id")) %>%
  filter(ee_site_id %in% jan_properties, circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat")) %>%
  mutate(min_t = min_t + hours(tz_utc_offset),
    month=str_extract(min_t, "(?<=-)[0-9]{2}"),
    hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
    date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>%
  group_by(ee_site_id, date, month, hour, circuit_label_type_desc) %>%
  summarize(kW_hour = sum(power)) %>%
  rbind(heating)
}

heating2 <- heating %>% 
    mutate(month = case_when(
      month == "01" ~ "Jan",
      month == "02" ~ "Feb",
      month == "03" ~ "Mar",
      month == "04" ~ "Apr",
      month == "05" ~ "May",
      month == "06" ~ "Jun",
      month == "07" ~ "Jul",
      month == "08" ~ "Aug",
      month == "09" ~ "Sep",
      month == "10" ~ "Oct",
      month == "11" ~ "Nov",
      month == "12" ~ "Dec"))

heating2$month <- factor(heating2$month, levels = month.abb)

heating2 %>% 
  filter(circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat")) %>% 
  ggplot() + geom_boxplot(aes(x=circuit_label_type_desc, y=kW_hour, color=circuit_label_type_desc))+
  facet_wrap(~month)+
  scale_color_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Ducted Heatpump (34 sites)", "Ductless Heatpump (9 sites)", "Electric Baseboard Heaters (16 sites)", "Electric Furnace (39 sites)", "Gas Furnance (Fan Energy) (24 sites)", "Other Zonal Heat (11 sites)"))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank())+
  labs(title = "2019 EULR Power Used by Heaters", y = "Load/Energy (kWh)", x = NULL, color = NULL)

heating2 %>% 
  filter(circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat")) %>% 
  ggplot() + geom_boxplot(aes(x=circuit_label_type_desc, y=kW_hour, color=circuit_label_type_desc), size = .3)+
  facet_wrap(~month)+
  scale_color_manual(values = wes_palette("Darjeeling1", 6, type = "continuous"),
                    labels = c("Ducted Heatpump (34 sites)", "Ductless Heatpump (9 sites)", "Electric Baseboard Heaters (16 sites)", "Electric Furnace (39 sites)", "Gas Furnance (Fan Energy) (24 sites)", "Other Zonal Heat (11 sites)"))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank())+
  ylim(0, 15)+
  labs(title = "2019 EULR Power Used by Heaters", subtitle = "This plot does not include outliers over 15 kWh", y = "Load/Energy (kWh)", x = NULL, color = NULL)
```


```{r AC plot}
power_data_same_sites %>% 
  filter(category == "AC") %>% 
  group_by(month, date, hz, cz) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  filter(mean_power > 0.15) %>% 
  left_join(temp_avg3, by = c("date", "hz", "cz")) %>% 
  mutate(cz = as.factor(cz)) %>% 
  ggplot() + geom_point(aes(x=mean_temp, y=mean_power, color = cz), size = .75)+
  facet_wrap(~month)+
  scale_color_manual(values = c("#00A08A", "#F2AD00", "#FF0000"))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power Used by All Cooling", y = "Load/Energy (kWh)", x = "Mean Outdoor Temperature (F)", color = "Cooling Zone", caption = "Each dot represents the average power and temperature, respectively, for one day")

```

```{r}
jan_power <- read_month_data("2019_Q1_v3/Jan", "/power/") %>% 
  left_join(points, by = c("ee_site_id", "regname")) %>% 
  left_join(sites, by = c("ee_site_id")) %>% 
  left_join(read_month_data("2019_Q1_v3/Jan", "/temperature/"), by = c("ee_site_id", "min_t")) 

jan_power2 <- jan_power%>% 
  na.omit() %>% 
  left_join(temp_points, by = c("ee_site_id", "transmitter_code")) %>% 
  filter(ee_site_id %in% jan_properties, circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat"), interior_exterior==2) %>% 
  mutate(min_t = min_t + hours(tz_utc_offset),
    month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
    hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
    date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
  group_by(ee_site_id, date, month, hour, circuit_label_type_desc) %>% 
  summarize(kW_hour = sum(power), mean_outdoor_temp = mean(temp)) %>% 
  filter(month == "01") %>% 
  mutate(month = "Jan")

aug_power <- read_month_data("2019_Q3_v3/Aug", "/power/") %>% 
  left_join(points, by = c("ee_site_id", "regname")) %>% 
  left_join(sites, by = c("ee_site_id")) %>% 
  left_join(read_month_data("2019_Q3_v3/Aug", "/temperature/"), by = c("ee_site_id", "min_t")) %>% 
  na.omit() %>% 
  left_join(temp_points, by = c("ee_site_id", "transmitter_code")) %>% 
  filter(ee_site_id %in% jan_properties, circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat"), interior_exterior==2) %>% 
  mutate(min_t = min_t + hours(tz_utc_offset),
    month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
    hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
    date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
  group_by(ee_site_id, date, month, hour, circuit_label_type_desc) %>% 
  summarize(kW_hour = sum(power), mean_outdoor_temp = mean(temp)) %>% 
  filter(month == "08") %>% 
  mutate(month = "Aug")


jan_plot <- jan_power2 %>% 
  #filter(kW_hour > 0.1) %>% 
  mutate(circuit_label_type_desc = case_when(
    circuit_label_type_desc == "Electric Baseboard Heaters" ~ "Electric\nBaseboard Heaters",
    circuit_label_type_desc == "Gas Furnace (Component)" ~ "Gas Furnace\n(Component)",
    TRUE ~ circuit_label_type_desc)) %>% 
  ggplot(aes(x=mean_outdoor_temp, y = kW_hour))+
  geom_point(color = "#257BA0", size = .75)+
  facet_wrap(~circuit_label_type_desc, nrow = 1)+
  ggplot2::theme_bw() +
  scale_x_continuous(limits = c(2, 115), breaks = c(30, 60, 90)) + 
  ylim(c(0, 53)) +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "January Power Used by Different Heaters by Temperature", y = "Load/Energy (kWh)", x = NULL) #+
  #theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

aug_plot <- aug_power %>% 
  #filter(kW_hour > 0.1) %>% 
  mutate(circuit_label_type_desc = case_when(
    circuit_label_type_desc == "Electric Baseboard Heaters" ~ "Electric\nBaseboard Heaters",
    circuit_label_type_desc == "Gas Furnace (Component)" ~ "Gas Furnace\n(Component)",
    TRUE ~ circuit_label_type_desc)) %>% 
  ggplot(aes(x=mean_outdoor_temp, y = kW_hour))+
  geom_point(color = "#257BA0", size = .75)+
  facet_wrap(~circuit_label_type_desc, nrow = 1)+
  ggplot2::theme_bw() +
    scale_x_continuous(limits = c(2, 115), breaks = c(30, 60, 90)) + 
  ylim(c(0, 53)) +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "August Power Used by Different Heaters by Temperature", y = "Load/Energy (kWh)", x = "Mean Outdoor Temperature (F)")


jan_plot / aug_plot
```


```{r}
# temp_heating <- NULL
# 
# for (month in mon_list){
#   temp_heating <- read_month_data(month, "/power/") %>% 
#   left_join(points, by = c("ee_site_id", "regname")) %>% 
#   left_join(sites, by = c("ee_site_id")) %>% 
#   left_join(read_month_data(month, "/temperature/"), by = c("ee_site_id", "min_t")) %>% 
#   na.omit() %>% 
#   left_join(temp_points, by = c("ee_site_id", "transmitter_code")) %>% 
#   filter(ee_site_id %in% jan_properties, circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump"), interior_exterior==2) %>% 
#   mutate(min_t = min_t + hours(tz_utc_offset),
#     month=str_extract(min_t, "(?<=-)[0-9]{2}"), 
#     hour = parse_number(stringr::str_extract(min_t,"[0-9]{2}(?=:)")),
#     date = lubridate::ymd(stringr::str_extract(min_t, "[0-9\\-]*(?= )"))) %>% 
#   group_by(ee_site_id, date, month, hour, circuit_label_type_desc) %>% 
#   summarize(kW_hour = sum(power), mean_outdoor_temp = mean(temp)) %>% 
#   rbind(temp_heating)
# }

temp_heating %>% 
  filter(kW_hour < 20) %>% 
  mutate(temp_cat = case_when(
    mean_outdoor_temp <= 15 ~ "< 15",
    mean_outdoor_temp <= 25 ~ "15-25",
    mean_outdoor_temp <= 35 ~ "25-35",
    mean_outdoor_temp <= 45 ~ "35-45",
    mean_outdoor_temp <= 55 ~ "45-55",
    mean_outdoor_temp <= 65 ~ "55-65",
    mean_outdoor_temp <= 75 ~ "65-75",
    mean_outdoor_temp <= 85 ~ "75-85",
    mean_outdoor_temp <= 95 ~ "85-95",
    mean_outdoor_temp > 95 ~ "95+")) %>% 
  #filter(kW_hour > 0.1) %>% 
  ggplot(aes(x=temp_cat, y = kW_hour))+
  geom_boxplot(color = "#257BA0", size = .75)+
  facet_wrap(~circuit_label_type_desc, nrow = 2)+
  ggplot2::theme_bw() +
  #scale_x_continuous(limits = c(2, 115), breaks = c(30, 60, 90)) + 
  #ylim(c(0, 53)) +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "Power Used by Heaters by Temperature", y = "Load/Energy (kWh)", x = "Temperature (F)") 

temp_heating %>% 
  filter(kW_hour < 20) %>% 
  mutate(temp_cat = case_when(
    mean_outdoor_temp <= 15 ~ "< 15",
    mean_outdoor_temp <= 25 ~ "15-25",
    mean_outdoor_temp <= 35 ~ "25-35",
    mean_outdoor_temp <= 45 ~ "35-45",
    mean_outdoor_temp <= 55 ~ "45-55",
    mean_outdoor_temp <= 65 ~ "55-65",
    mean_outdoor_temp <= 75 ~ "65-75",
    mean_outdoor_temp <= 85 ~ "75-85",
    mean_outdoor_temp <= 95 ~ "85-95",
    mean_outdoor_temp > 95 ~ "95+")) %>% 
  #filter(kW_hour > 0.1) %>% 
  ggplot(aes(x=temp_cat))+
  geom_bar(fill = "#257BA0", stat = "count")+
  facet_wrap(~circuit_label_type_desc, nrow = 2)+
  ggplot2::theme_bw() +
  #scale_x_continuous(limits = c(2, 115), breaks = c(30, 60, 90)) + 
  #ylim(c(0, 53)) +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "Power Used by Heaters by Temperature", y = "Number of Observations", x = "Temperature (F)") 

```


```{r LEFT OFF HERE!!!!}
power_data_same_sites %>% 
  #mutate(hz = str_c("HZ ", hz), cz = str_c("CZ ", cz)) %>% 
  filter(category == "Heating") %>% 
  left_join(temperature_data, by = c("date", "hour", "month", "hz", "cz")) %>% 
  group_by(date, circuit_label_type_desc) %>% 
  summarize(mean_temp = mean(mean_outdoor_temp), mean_power = mean(mean_power)) %>% 
  filter(mean_power > 0.1) %>% 
  mutate(circuit_label_type_desc = case_when(
    circuit_label_type_desc == "Electric Baseboard Heaters" ~ "Electric\nBaseboard Heaters",
    circuit_label_type_desc == "Gas Furnace (Component)" ~ "Gas Furnace\n(Component)",
    TRUE ~ circuit_label_type_desc)) %>% 
  ggplot(aes(x=mean_temp, y = mean_power))+
  geom_point(color = "#257BA0", size = .75)+
  facet_wrap(~circuit_label_type_desc)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power Used by Different Heaters by Temperature", y = "Mean Power (kWh)", x = "Mean Outdoor Temperature (F)", caption = "Each dot represents the average power and temperature, respectively, for one heating type for one day")
```


```{r}
# power_data2 %>% 
#   group_by(hour, hz, cz) %>% 
#   summarize(mean_kW = mean(mean_power)) %>% 
#   mutate(hz = str_c("HZ ", hz), cz = str_c("CZ ", cz)) %>% 
#   ggplot2::ggplot(aes(x=hour, y = mean_kW)) + 
#   ggplot2::geom_line(size = 1.05, color = "#257BA0") +
#   ggplot2::theme_bw() +
#   facet_grid(hz~cz)+
# 
#     #make breaks align with day breaks and clean labels
#     ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
#     ggplot2::labs(title = "2019 NEEA Home Energy Power Data by Cooling and Heating Zones", subtitle = stringr::str_c("Average Hourly Total Consumption"), y = "Mean Power (kWh)", x = "Hour") +
# 
#     #customize fonts to those in RR style guide
#     ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
#                    plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

power_data_same_sites %>% 
  group_by(hour, hz, cz) %>% 
  summarize(mean_kW = mean(mean_power)) %>% 
  mutate(hz = str_c("HZ ", hz), cz = str_c("CZ ", cz)) %>% 
  ggplot2::ggplot(aes(x=hour, y = mean_kW)) + 
  ggplot2::geom_line(size = 1.05, color = "#257BA0") +
  ggplot2::theme_bw() +
  facet_grid(cz~hz)+

    #make breaks align with day breaks and clean labels
    ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
    ggplot2::labs(title = "2019 EULR Home Energy Power Data by Cooling and Heating Zones", subtitle = stringr::str_c("Average Hourly Total Consumption"), y = "Mean Power (kWh)", x = "Hour") +

    #customize fonts to those in RR style guide
    ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
                   plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

dat_text <- sites %>% filter(ee_site_id %in% jan_properties) %>% 
  group_by(hz, cz) %>% 
  summarize(num = n()) %>% 
  mutate(hz = str_c("HZ ", hz), cz = str_c("CZ ", cz), 
         label = str_c(num, " sites"))

power_data_same_sites %>% 
  group_by(hour, category, hz, cz) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  mutate(hz = str_c("HZ ", hz), cz = str_c("CZ ", cz)) %>% 
  filter(!is.na(category), category != "Mains") %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=category), stat = "identity")+
  facet_grid(cz~hz)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Month by Circuit Category (Same Sites)", y = "Load/Energy (kWh)", x = "Hour", fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = c("#5BBCD6", "#FF0000", "#91A737", "#F49C00", "#32806E"),
                    labels = c("AC (22 sites)", "Heating (73 sites)", "Other (73 sites)", "Solar (4 sites)", "Water Heaters (53 sites)"))+ #, "#257BA0"
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  geom_label(data = dat_text, mapping = aes(x = 18, y = 5.8, label = label), alpha = .6)
  # geom_label(data = dat_text, aes(x = 18, y = 5.5, label=label),
  #                      label.size = NA,  
  #                      label.padding=.1, 
  #                      na.rm=TRUE,
  #                      fill = alpha(c("white"),0.5))
```

```{r}
power_data_same_sites %>% 
  group_by(hour, month) %>% 
  summarize(mean_kW = mean(mean_power)) %>% 
  ggplot(aes(x=hour, y = mean_kW)) + 
  ggplot2::geom_line(size = 1.05, color = "#257BA0") +
  ggplot2::theme_bw() +
  facet_wrap(~month)+

    #make breaks align with day breaks and clean labels
    ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
    ggplot2::labs(title = "2019 EULR Home Energy Power Data by Month", subtitle = stringr::str_c("Average Hourly Total Consumption"), y = "Load/Energy (kWh)", x = "Hour") +

    #customize fonts to those in RR style guide
    ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
                   plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))
```


#plots 2/13

```{r}
sites %>% 
  filter(ee_site_id %in% jan_properties) %>% 
  group_by(hz) %>% 
  summarize(n())

power_data_same_sites %>% 
  group_by(hz, category) %>% 
  mutate(hz = case_when(
    hz == 1 ~ "Heating Zone 1\n(54 sites)",
    hz == 2 ~ "Heating Zone 2\n(16 sites)",
    hz == 3 ~ "Heating Zone 3\n(3 sites)")) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  filter(!is.na(category), category != "Mains", category != "Solar") %>% 
  ggplot() + geom_bar(aes(x=hz, y=mean_power, fill=category), stat = "identity", position = "dodge")+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Circuit Category by Heating Zone", y = "Load/Energy (kWh)", x = NULL, fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = c("#5BBCD6", "#FF0000", "#91A737", "#32806E"))+
  theme(axis.text.x = element_text(size = 11, color = "black"))
```

```{r}
hz_heaters <- sites %>% 
  filter(ee_site_id %in% jan_properties) %>% 
  left_join(points, by = c("ee_site_id")) %>% 
  filter(circuit_label_type_desc %in% c("Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Gas Furnace (Component)", "Other Zonal Heat")) %>% 
  group_by(hz, circuit_label_type_desc) %>% 
  summarize(n()) %>% 
  pivot_wider(id_cols = circuit_label_type_desc, names_from = hz, values_from = `n()`) %>% 
  rename(`Heating Type` = circuit_label_type_desc, `HZ 1` = `1`, `HZ 2` = `2`, `HZ 3` = `3`)

hz_heaters[is.na(hz_heaters)] = 0

zeros <- data.frame(hz = c(2, 3, 3, 3, 3, 3), circuit_label_type_desc = c("Ductless Heatpump", "Ducted Heatpump", "Ductless Heatpump", "Electric Baseboard Heaters", "Electric Furnace", "Other Zonal Heat"), mean_power = 0)

power_data_same_sites %>% 
  filter(category == "Heating") %>% 
  group_by(hz, circuit_label_type_desc) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  full_join(zeros, by = c("hz", "circuit_label_type_desc", "mean_power")) %>% 
  mutate(hz = case_when(
    hz == 1 ~ "Heating Zone 1\n(54 sites)",
    hz == 2 ~ "Heating Zone 2\n(16 sites)",
    hz == 3 ~ "Heating Zone 3\n(3 sites)"),
    circuit_label_type_desc = case_when(
      circuit_label_type_desc == "Gas Furnace (Component)" ~ "Gas Furnance (Fan Energy)",
      TRUE ~ circuit_label_type_desc)) %>% 
  ggplot() + geom_bar(aes(x=hz, y=mean_power, fill=circuit_label_type_desc), stat = "identity", position = "dodge")+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Heating Category by Heating Zone", y = "Load/Energy (kWh)", x = NULL, fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = wes_palette("Darjeeling1", 10, type = "continuous"))+
  theme(axis.text.x = element_text(size = 11, color = "black"))
```

```{r}

power_data2 %>% 
  filter(category == "Mains") %>% 
  group_by(month, hour, circuit_label_type_desc) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(aes(x = hour, y = mean_power, color = circuit_label_type_desc))+
  facet_wrap(~month)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Hour", y = "Mean Power (kWh)", x = "Hour", color = NULL)+
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  scale_color_manual(values = c("#257BA0", "#93B83D"))

```

```{r}
power_temp <- temperature_data2 %>%  #power_data2 %>% 
  #mutate(hz = parse_number(hz), cz = parse_number(cz)) %>% 
  right_join(power_data_same_sites, by = c("date", "month", "hour", "hz", "cz")) %>% 
  group_by(month, hour) %>%
  summarize(mean_temp = mean(na.omit(mean_outdoor_temp)), mean_power = mean(na.omit(mean_power)))
power_temp$month <- factor(power_temp$month, levels = month.abb)
```

```{r}
spr_temp <- power_temp %>% 
  filter(month %in% c("Jan", "Feb", "Mar", "Apr", "May", "Jun")) %>% 
  ggplot() + 
  geom_line(aes(y=mean_temp, x = hour), color = "#257BA0")+
  facet_wrap(~month, nrow = 1)+
  scale_y_continuous(breaks=c(40, 60, 80), limits = c(27, 84))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        plot.title = element_markdown()) +
  labs(x = NULL, y = NULL, title = "EULR Average Hourly <span style='color:#257BA0'>Temperature (F)</span> and <span style='color:#93B83D'>Load/Energy (kWh)</span> in 2019")

spr_power <- power_temp %>% 
  filter(month %in% c("Jan", "Feb", "Mar", "Apr", "May", "Jun")) %>% 
  ggplot() + 
  geom_line(aes(y=mean_power, x = hour), color = "#93B83D")+
  facet_wrap(~month, nrow = 1)+
  labs(x = NULL, y = NULL)+
  scale_y_continuous(breaks=c(0.5, 1.0, 1.5, 2.0), limits = c(0.38, 2))+
  scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

fall_temp <- power_temp %>% 
  filter(month %in% c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) %>% 
  ggplot() + 
  geom_line(aes(y=mean_temp, x = hour), color = "#257BA0")+
  facet_wrap(~month, nrow = 1) +
  labs(x = NULL, y = NULL)+
  theme(axis.text.x = element_blank(), axis.ticks = element_blank())+
  scale_y_continuous(breaks=c(40, 60, 80), limits = c(27, 84))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

fall_power <- power_temp %>% 
  filter(month %in% c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) %>% 
  ggplot() + 
  geom_line(aes(y=mean_power, x = hour), color = "#93B83D")+
  facet_wrap(~month, nrow = 1)+
  labs(x = "Hour", y = NULL)+
  scale_x_continuous(breaks=c(1, 6, 12, 18, 24))+
  scale_y_continuous(breaks=c(0.5, 1.0, 1.5, 2.0), limits = c(0.38, 2))+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

(spr_temp / spr_power / fall_temp / fall_power) + plot_layout(nrow = 4)#, heights = c(5, 5, 1, 5, 5))
```


```{r}
power_data_same_sites %>%
  filter(circuit_label_type_desc == "Lighting and/or Outlets") %>% 
  group_by(hour, month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(aes(x = hour, y = mean_power, color = month), size = 1.1)+
  scale_color_manual(values = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A", "#d9d36a", "#B15928"))+
  theme_bw()+
  labs(x= "Hour", y = "Load/Energy (kWh)", title = "Hourly Lighting/Outlet Usage for a Given Month", subtitle = "Based off of NREL Figure 1", color = NULL)+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  scale_x_continuous(breaks=c(1, 6, 12, 18, 24))

power_data_same_sites %>%
  filter(circuit_label_type_desc == "Lighting and/or Outlets") %>% 
  group_by(hour, month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(aes(x = hour, y = mean_power), size = 1.1, color = "#93B83D")+
  theme_bw()+
  labs(x= "Hour", y = "Load/Energy (kWh)", title = "Hourly Lighting/Outlet Usage for a Given Month")+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  facet_wrap(~month)+
  scale_x_continuous(breaks=c(1, 6, 12, 18, 24))

power_data_same_sites %>%
  filter(circuit_label_type_desc == "Lighting and/or Outlets") %>% 
  group_by(hour) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(aes(x = hour, y = mean_power), size = 1.1, color = "#93B83D")+
  theme_bw()+
  labs(x= "Hour", y = "Load/Energy (kWh)", title = "Hourly Lighting/Outlet Usage")+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  scale_x_continuous(breaks=c(1, 6, 12, 18, 24))

```

```{r}


dhw <- power_data2 %>% 
  filter(str_detect(circuit_label_type_desc, "(W|w)ater")) %>% 
  group_by(month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(group = 1, aes(x = month, y = mean_power), color = "#93B83D", size = 1.1)+
  theme_bw()+
  labs(x= NULL, y = "Mean Power (kWh)", title = "Power Usage of Water Heaters for a Given Month", subtitle = "Based off of NREL Figure 14", color = NULL)+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

monthly_temp <- temperature_data2 %>% 
  group_by(month) %>% 
  summarize(mean_outdoor_temp = mean(mean_outdoor_temp), mean_indoor_temp = mean(mean_indoor_temp)) %>% 
  pivot_longer(!month, names_to = "type", values_to = "mean_temp") %>% 
  ggplot() + geom_line(aes(x=month, y = mean_temp, color = type, group = type), size = 1.1)+ #color = "#257BA0",
  #geom_line(group = 1, aes(x=month, y = mean_indoor_temp), color = "#4EACDB", size = 1.1)+
  scale_color_manual(values = c("#4EACDB", "#257BA0"), labels = c("Indoor", "Outdoor")) + 
  theme_bw()+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  theme(plot.title = element_markdown())+
  labs(x= "Month", y = "Mean Temperature (F)", title = "Average Monthly Temperature", color = NULL)

dhw/monthly_temp

```


```{r}
#power_data_same_sites$month <- factor(power_data_same_sites$month, levels = month.abb)

dhw <- power_data_same_sites %>% 
  filter(str_detect(circuit_label_type_desc, "(W|w)ater")) %>% 
  group_by(month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(group = 1, aes(x = month, y = mean_power), color = "#93B83D", size = 1.1)+
  theme_bw()+
  labs(x= NULL, y = "Load/Energy (kWh)", title = "Power Usage of Water Heaters for a Given Month", subtitle = "Based off of NREL Figure 14", color = NULL)+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))

monthly_temp <- temperature_data2 %>% 
  group_by(month) %>% 
  summarize(mean_outdoor_temp = mean(mean_outdoor_temp), mean_indoor_temp = mean(mean_indoor_temp)) %>% 
  pivot_longer(!month, names_to = "type", values_to = "mean_temp") %>% 
  ggplot() + geom_line(aes(x=month, y = mean_temp, color = type, group = type), size = 1.1)+ #color = "#257BA0",
  #geom_line(group = 1, aes(x=month, y = mean_indoor_temp), color = "#4EACDB", size = 1.1)+
  scale_color_manual(values = c("#4EACDB", "#257BA0"), labels = c("Indoor", "Outdoor")) + 
  theme_bw()+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  theme(plot.title = element_markdown())+
  labs(x= "Month", y = "Mean Temperature (F)", title = "Average Monthly Temperature", color = NULL)

dhw/monthly_temp
```



```{r look at DHW}
dhw_same <- power_data_same_sites %>% 
  filter(str_detect(circuit_label_type_desc, "(W|w)ater")) %>% 
  group_by(month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(group = 1, aes(x = month, y = mean_power), color = "#93B83D", size = 1.1)+
  theme_bw()+
  ylim(0.7, 1.7)+
  labs(x= NULL, y = "Mean Power (kWh)", title = "Power Usage of Water Heaters for a Given Month (Same Sites)", subtitle = "Based off of NREL Figure 14", color = NULL)+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))


dhw_all <- power_data2 %>% 
  filter(str_detect(circuit_label_type_desc, "(W|w)ater")) %>% 
  group_by(month) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  ggplot() + geom_line(group = 1, aes(x = month, y = mean_power), color = "#93B83D", size = 1.1)+
  ylim(0.7, 1.7)+
  theme_bw()+
  labs(x= NULL, y = "Mean Power (kWh)", title = "Power Usage of Water Heaters for a Given Month (All Sites)", subtitle = "Based off of NREL Figure 14", color = NULL)+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))


by_cat_same <- power_data_same_sites %>% 
  group_by(hour, category, month) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  filter(!is.na(category), category != "Mains") %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=category), stat = "identity")+
  facet_wrap(~month)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Month by Circuit Category (Same Sites)", y = "Mean Power (kWh)", x = "Hour", fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = c("#5BBCD6", "#FF0000", "#91A737", "#F49C00", "#32806E"))+ #, "#257BA0"
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))


by_cat_all <- power_data2 %>% 
  group_by(hour, category, month) %>% 
  #mutate(cz = as.factor(cz)) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
  filter(!is.na(category), category != "Mains") %>% 
  ggplot() + geom_bar(aes(x=hour, y=mean_power, fill=category), stat = "identity")+
  facet_wrap(~month)+
  ggplot2::theme_bw() +
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
  labs(title = "2019 EULR Average Power by Month by Circuit Category (All Sites)", y = "Mean Power (kWh)", x = "Hour", fill = NULL)+
  #scale_fill_manual(values = c("#62B2B9", "#A06CB2", "#D42142", "#2B74A1", "#3F8F55", "#EBBA28"))
  scale_fill_manual(values = c("#5BBCD6", "#FF0000", "#91A737", "#F49C00", "#32806E"))+ #, "#257BA0"
  ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))

(dhw_all + by_cat_all ) / (dhw_same + by_cat_same)
```

```{r}
plot_hourly_data <- function(circuit_type){
  circuit_type_data <- power_data_same_sites %>% 
  filter(circuit_label_type_desc == circuit_type) %>% 
  group_by(hour, circuit_label_type_desc) %>% 
  summarize(mean_power = mean(mean_power)) %>% 
    left_join(num_uses, by = "circuit_label_type_desc")
  
  num_circuit_type_uses <- unique(circuit_type_data$number)
  
  ggplot(circuit_type_data) + geom_line(group = 1, aes(x = hour, y = mean_power), color = "#93B83D", size = 1.1)+
  theme_bw()+
  labs(x= "Hour", y = "Load/Energy (kWh)", title = str_c("2019 EULR Average Hourly Power Usage — ", circuit_type, "s"), subtitle = str_c(circuit_type, "s reported at ", num_circuit_type_uses, " sites"))+
  ggplot2::theme(text = ggplot2::element_text(family = choose_font(c("Muli", "sans"))),
          plot.title=ggplot2::element_text(family = choose_font(c("Roboto Slab", "serif")), face="bold"))+
    ggplot2::scale_x_continuous(breaks=c(1, 6, 12, 18, 24))
}

appliances_other <- c("Clothes Dryer", "Clothes Washer", "Dishwasher", "Microwave", "Refrigerator/Freezer", "Stove/Oven/Range", "Electric Vehicle Charger", "Hot Tub")

map(appliances_other, plot_hourly_data)



```


